// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "@hey-api/client-axios";
import type {
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenError,
  LoginLoginAccessTokenResponse,
  LoginTestTokenError,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordError,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordError,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentError,
  LoginRecoverPasswordHtmlContentResponse,
  UsersReadUsersData,
  UsersReadUsersError,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserError,
  UsersCreateUserResponse,
  UsersReadWaitlistUsersData,
  UsersReadWaitlistUsersError,
  UsersReadWaitlistUsersResponse,
  UsersReadUserMeError,
  UsersReadUserMeResponse,
  UsersDeleteUserMeError,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeError,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeError,
  UsersUpdatePasswordMeResponse,
  UsersRegisterUserData,
  UsersRegisterUserError,
  UsersRegisterUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdError,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserError,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserError,
  UsersDeleteUserResponse,
  UsersApproveUserData,
  UsersApproveUserError,
  UsersApproveUserResponse,
  UsersRejectUserData,
  UsersRejectUserError,
  UsersRejectUserResponse,
  UtilsTestEmailData,
  UtilsTestEmailError,
  UtilsTestEmailResponse,
  UtilsHealthCheckError,
  UtilsHealthCheckResponse,
  ItemsReadItemsData,
  ItemsReadItemsError,
  ItemsReadItemsResponse,
  ItemsCreateItemData,
  ItemsCreateItemError,
  ItemsCreateItemResponse,
  ItemsReadItemData,
  ItemsReadItemError,
  ItemsReadItemResponse,
  ItemsUpdateItemData,
  ItemsUpdateItemError,
  ItemsUpdateItemResponse,
  ItemsDeleteItemData,
  ItemsDeleteItemError,
  ItemsDeleteItemResponse,
  AgentAgentChatProxyError,
  AgentAgentChatProxyResponse,
  UploadsUploadFilesData,
  UploadsUploadFilesError,
  UploadsUploadFilesResponse,
  UploadsListDocumentsData,
  UploadsListDocumentsError,
  UploadsListDocumentsResponse,
  UploadsDeleteDocumentsData,
  UploadsDeleteDocumentsError,
  UploadsDeleteDocumentsResponse,
  UploadsGetDocumentData,
  UploadsGetDocumentError,
  UploadsGetDocumentResponse,
  UploadsDeleteDocumentData,
  UploadsDeleteDocumentError,
  UploadsDeleteDocumentResponse,
  UploadsGetPresignedUrlData,
  UploadsGetPresignedUrlError,
  UploadsGetPresignedUrlResponse,
  UploadsCheckDataConsistencyError,
  UploadsCheckDataConsistencyResponse,
  UploadsCleanupFilesData,
  UploadsCleanupFilesError,
  UploadsCleanupFilesResponse,
  UploadsCleanupRecordsData,
  UploadsCleanupRecordsError,
  UploadsCleanupRecordsResponse,
  UploadsFullCleanupData,
  UploadsFullCleanupError,
  UploadsFullCleanupResponse,
  SearchSearchDocumentsData,
  SearchSearchDocumentsError,
  SearchSearchDocumentsResponse,
  SearchSearchHealthError,
  SearchSearchHealthResponse,
  SourcesListSourcesData,
  SourcesListSourcesError,
  SourcesListSourcesResponse,
  SourcesCreateSourceData,
  SourcesCreateSourceError,
  SourcesCreateSourceResponse,
  SourcesGetSourceData,
  SourcesGetSourceError,
  SourcesGetSourceResponse,
  SourcesUpdateSourceData,
  SourcesUpdateSourceError,
  SourcesUpdateSourceResponse,
  SourcesDeleteSourceData,
  SourcesDeleteSourceError,
  SourcesDeleteSourceResponse,
  NotebooksListNotebooksData,
  NotebooksListNotebooksError,
  NotebooksListNotebooksResponse,
  NotebooksCreateNotebookData,
  NotebooksCreateNotebookError,
  NotebooksCreateNotebookResponse,
  NotebooksGetNotebookData,
  NotebooksGetNotebookError,
  NotebooksGetNotebookResponse,
  NotebooksUpdateNotebookData,
  NotebooksUpdateNotebookError,
  NotebooksUpdateNotebookResponse,
  NotebooksDeleteNotebookData,
  NotebooksDeleteNotebookError,
  NotebooksDeleteNotebookResponse,
  NotebookMessagesListNotebookMessagesData,
  NotebookMessagesListNotebookMessagesError,
  NotebookMessagesListNotebookMessagesResponse,
  NotebookMessagesAddMessageToNotebookData,
  NotebookMessagesAddMessageToNotebookError,
  NotebookMessagesAddMessageToNotebookResponse,
  NotebookSourcesListNotebookSourcesData,
  NotebookSourcesListNotebookSourcesError,
  NotebookSourcesListNotebookSourcesResponse,
  NotebookSourcesAddSourceToNotebookData,
  NotebookSourcesAddSourceToNotebookError,
  NotebookSourcesAddSourceToNotebookResponse,
  NotebookSourcesRemoveSourceFromNotebookData,
  NotebookSourcesRemoveSourceFromNotebookError,
  NotebookSourcesRemoveSourceFromNotebookResponse,
  NotebookSourcesUpdateNotebookSourceData,
  NotebookSourcesUpdateNotebookSourceError,
  NotebookSourcesUpdateNotebookSourceResponse,
  PrivateCreateUserData,
  PrivateCreateUserError,
  PrivateCreateUserResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Login Access Token
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginLoginAccessToken = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<LoginLoginAccessTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginLoginAccessTokenResponse,
    LoginLoginAccessTokenError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/api/v1/login/access-token",
  });
};

/**
 * Test Token
 * Test access token
 */
export const loginTestToken = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginTestTokenResponse,
    LoginTestTokenError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/login/test-token",
  });
};

/**
 * Recover Password
 * Password Recovery
 */
export const loginRecoverPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<LoginRecoverPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginRecoverPasswordResponse,
    LoginRecoverPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/password-recovery/{email}",
  });
};

/**
 * Reset Password
 * Reset password
 */
export const loginResetPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<LoginResetPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginResetPasswordResponse,
    LoginResetPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/reset-password/",
  });
};

/**
 * Recover Password Html Content
 * HTML Content for Password Recovery
 */
export const loginRecoverPasswordHtmlContent = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    LoginRecoverPasswordHtmlContentData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    LoginRecoverPasswordHtmlContentResponse,
    LoginRecoverPasswordHtmlContentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/password-recovery-html-content/{email}",
  });
};

/**
 * Read Users
 * Retrieve users.
 */
export const usersReadUsers = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<UsersReadUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersReadUsersResponse,
    UsersReadUsersError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/",
  });
};

/**
 * Create User
 * Create new user.
 */
export const usersCreateUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersCreateUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UsersCreateUserResponse,
    UsersCreateUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/",
  });
};

/**
 * Read Waitlist Users
 * Retrieve users pending approval (waitlist).
 */
export const usersReadWaitlistUsers = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<UsersReadWaitlistUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersReadWaitlistUsersResponse,
    UsersReadWaitlistUsersError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/waitlist",
  });
};

/**
 * Read User Me
 * Get current user.
 */
export const usersReadUserMe = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersReadUserMeResponse,
    UsersReadUserMeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Delete User Me
 * Delete own user.
 */
export const usersDeleteUserMe = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UsersDeleteUserMeResponse,
    UsersDeleteUserMeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Update User Me
 * Update own user.
 */
export const usersUpdateUserMe = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUpdateUserMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersUpdateUserMeResponse,
    UsersUpdateUserMeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Update Password Me
 * Update own password.
 */
export const usersUpdatePasswordMe = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUpdatePasswordMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersUpdatePasswordMeResponse,
    UsersUpdatePasswordMeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me/password",
  });
};

/**
 * Register User
 * Create new user without the need to be logged in.
 */
export const usersRegisterUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersRegisterUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UsersRegisterUserResponse,
    UsersRegisterUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/signup",
  });
};

/**
 * Read User By Id
 * Get a specific user by id.
 */
export const usersReadUserById = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersReadUserByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersReadUserByIdResponse,
    UsersReadUserByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{user_id}",
  });
};

/**
 * Update User
 * Update a user.
 */
export const usersUpdateUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUpdateUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersUpdateUserResponse,
    UsersUpdateUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{user_id}",
  });
};

/**
 * Delete User
 * Delete a user.
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UsersDeleteUserResponse,
    UsersDeleteUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{user_id}",
  });
};

/**
 * Approve User
 * Approve a user from the waitlist.
 */
export const usersApproveUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersApproveUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersApproveUserResponse,
    UsersApproveUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{user_id}/approve",
  });
};

/**
 * Reject User
 * Reject a user from the waitlist (delete the user).
 */
export const usersRejectUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersRejectUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersRejectUserResponse,
    UsersRejectUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{user_id}/reject",
  });
};

/**
 * Test Email
 * Test emails.
 */
export const utilsTestEmail = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UtilsTestEmailData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UtilsTestEmailResponse,
    UtilsTestEmailError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/utils/test-email/",
  });
};

/**
 * Health Check
 */
export const utilsHealthCheck = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UtilsHealthCheckResponse,
    UtilsHealthCheckError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/utils/health-check/",
  });
};

/**
 * Read Items
 * Retrieve items.
 */
export const itemsReadItems = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ItemsReadItemsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ItemsReadItemsResponse,
    ItemsReadItemsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/items/",
  });
};

/**
 * Create Item
 * Create new item.
 */
export const itemsCreateItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ItemsCreateItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ItemsCreateItemResponse,
    ItemsCreateItemError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/items/",
  });
};

/**
 * Read Item
 * Get item by ID.
 */
export const itemsReadItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ItemsReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ItemsReadItemResponse,
    ItemsReadItemError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/items/{id}",
  });
};

/**
 * Update Item
 * Update an item.
 */
export const itemsUpdateItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ItemsUpdateItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    ItemsUpdateItemResponse,
    ItemsUpdateItemError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/items/{id}",
  });
};

/**
 * Delete Item
 * Delete an item.
 */
export const itemsDeleteItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ItemsDeleteItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ItemsDeleteItemResponse,
    ItemsDeleteItemError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/items/{id}",
  });
};

/**
 * Agent Chat Proxy
 */
export const agentAgentChatProxy = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AgentAgentChatProxyResponse,
    AgentAgentChatProxyError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/agent/chat",
  });
};

/**
 * Upload Files
 * Upload multiple files with transactional safety and idempotency.
 *
 * This endpoint handles batch file uploads with comprehensive error handling:
 * - Each file is processed individually with its own transaction
 * - Failed uploads don't affect successful ones
 * - Duplicate files are detected and reported
 * - Detailed error reporting for each file
 *
 * Args:
 * session: Database session
 * current_user: Authenticated user
 * files: List of files to upload
 *
 * Returns:
 * Dict containing:
 * - documents: List of successfully uploaded documents
 * - failed_uploads: List of failed uploads with reasons
 * - message: Summary of operation results
 */
export const uploadsUploadFiles = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UploadsUploadFilesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadsUploadFilesResponse,
    UploadsUploadFilesError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/v1/uploads/files",
  });
};

/**
 * List Documents
 * List user's documents with pagination.
 *
 * Args:
 * session: Database session
 * current_user: Authenticated user
 * skip: Number of records to skip for pagination
 * limit: Maximum number of records to return
 *
 * Returns:
 * DocumentsPublic: Paginated list of user's documents
 */
export const uploadsListDocuments = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<UploadsListDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UploadsListDocumentsResponse,
    UploadsListDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/documents",
  });
};

/**
 * Delete Documents
 * Delete multiple documents with transactional safety.
 *
 * This endpoint handles batch deletions with individual error handling:
 * - Each document is deleted in its own transaction
 * - Failed deletions don't affect successful ones
 * - Detailed reporting of successes and failures
 *
 * Args:
 * session: Database session
 * current_user: Authenticated user
 * document_ids: List of document UUIDs to delete
 *
 * Returns:
 * Dict containing:
 * - message: Summary of operation results
 * - deleted_count: Number of successfully deleted documents
 * - total_requested: Total number of documents requested for deletion
 * - failed_deletions: List of failed deletions with reasons
 */
export const uploadsDeleteDocuments = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UploadsDeleteDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UploadsDeleteDocumentsResponse,
    UploadsDeleteDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/documents",
  });
};

/**
 * Get Document
 * Get a specific document by ID.
 *
 * Args:
 * session: Database session
 * current_user: Authenticated user
 * document_id: UUID of the document to retrieve
 *
 * Returns:
 * DocumentPublic: Document details
 */
export const uploadsGetDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UploadsGetDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UploadsGetDocumentResponse,
    UploadsGetDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/documents/{document_id}",
  });
};

/**
 * Delete Document
 * Delete a single document with transactional safety.
 *
 * Args:
 * session: Database session
 * current_user: Authenticated user
 * document_id: UUID of the document to delete
 *
 * Returns:
 * Dict containing success message and document_id
 */
export const uploadsDeleteDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UploadsDeleteDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UploadsDeleteDocumentResponse,
    UploadsDeleteDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/documents/{document_id}",
  });
};

/**
 * Get Presigned Url
 * Get a presigned URL for direct file access.
 *
 * Args:
 * current_user: Authenticated user
 * key: Object key in MinIO
 * expires_minutes: URL expiration time (1-1440 minutes)
 *
 * Returns:
 * Dict containing presigned URL and metadata
 */
export const uploadsGetPresignedUrl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UploadsGetPresignedUrlData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UploadsGetPresignedUrlResponse,
    UploadsGetPresignedUrlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/presign",
  });
};

/**
 * Check Data Consistency
 * Check data consistency between MinIO and PostgreSQL.
 * Only available to superusers for security.
 */
export const uploadsCheckDataConsistency = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UploadsCheckDataConsistencyResponse,
    UploadsCheckDataConsistencyError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/consistency-check",
  });
};

/**
 * Cleanup Files
 * Clean up orphaned MinIO files.
 *
 * This endpoint removes MinIO files that don't have corresponding database records:
 * - Scans MinIO storage for orphaned files
 * - Provides dry-run mode for safe testing
 * - Reports detailed cleanup results
 *
 * Args:
 * current_user: Authenticated user (must be superuser)
 * dry_run: If True, only report what would be deleted
 *
 * Returns:
 * Dict containing cleanup operation results
 *
 * Security: Superuser-only access required
 */
export const uploadsCleanupFiles = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<UploadsCleanupFilesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadsCleanupFilesResponse,
    UploadsCleanupFilesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/cleanup/orphaned-files",
  });
};

/**
 * Cleanup Records
 * Clean up orphaned database records.
 *
 * This endpoint removes database records that don't have corresponding MinIO files:
 * - Scans database for orphaned records
 * - Provides dry-run mode for safe testing
 * - Reports detailed cleanup results
 *
 * Args:
 * current_user: Authenticated user (must be superuser)
 * dry_run: If True, only report what would be deleted
 *
 * Returns:
 * Dict containing cleanup operation results
 *
 * Security: Superuser-only access required
 */
export const uploadsCleanupRecords = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<UploadsCleanupRecordsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadsCleanupRecordsResponse,
    UploadsCleanupRecordsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/cleanup/orphaned-records",
  });
};

/**
 * Full Cleanup
 * Run a full cleanup operation including consistency check and cleanup.
 *
 * This endpoint performs a comprehensive cleanup operation:
 * - Checks data consistency between MinIO and PostgreSQL
 * - Cleans up orphaned files and records
 * - Provides dry-run mode for safe testing
 * - Reports detailed results of all operations
 *
 * Args:
 * current_user: Authenticated user (must be superuser)
 * dry_run: If True, only report what would be cleaned
 *
 * Returns:
 * Dict containing complete cleanup operation results
 *
 * Security: Superuser-only access required
 */
export const uploadsFullCleanup = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<UploadsFullCleanupData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadsFullCleanupResponse,
    UploadsFullCleanupError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/uploads/cleanup/full",
  });
};

/**
 * Search Documents
 * Search documents using vector similarity.
 */
export const searchSearchDocuments = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SearchSearchDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SearchSearchDocumentsResponse,
    SearchSearchDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/search/documents",
  });
};

/**
 * Search Health
 * Check search service health.
 */
export const searchSearchHealth = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SearchSearchHealthResponse,
    SearchSearchHealthError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/search/health",
  });
};

/**
 * List Sources
 * List user's sources with optional filtering by type.
 * Includes notebook count for each source to show usage impact.
 */
export const sourcesListSources = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<SourcesListSourcesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SourcesListSourcesResponse,
    SourcesListSourcesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/sources/",
  });
};

/**
 * Create Source
 * Create a new source with validation and error handling.
 */
export const sourcesCreateSource = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SourcesCreateSourceData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SourcesCreateSourceResponse,
    SourcesCreateSourceError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/sources/",
  });
};

/**
 * Get Source
 * Get a specific source by ID with ownership verification.
 * Includes notebook count to show usage impact.
 */
export const sourcesGetSource = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SourcesGetSourceData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SourcesGetSourceResponse,
    SourcesGetSourceError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/sources/{source_id}",
  });
};

/**
 * Update Source
 * Update a source with ownership verification and validation.
 */
export const sourcesUpdateSource = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SourcesUpdateSourceData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    SourcesUpdateSourceResponse,
    SourcesUpdateSourceError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/sources/{source_id}",
  });
};

/**
 * Delete Source
 * Delete a source with comprehensive cleanup including storage.
 *
 * This endpoint now handles:
 * - Database deletion with cascade handling
 * - Qdrant cleanup for document and URL sources
 * - MinIO cleanup for document sources
 * - Proper error handling and rollback
 */
export const sourcesDeleteSource = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SourcesDeleteSourceData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    SourcesDeleteSourceResponse,
    SourcesDeleteSourceError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/sources/{source_id}",
  });
};

/**
 * List Notebooks
 * List user's notebooks with pagination and error handling.
 */
export const notebooksListNotebooks = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<NotebooksListNotebooksData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    NotebooksListNotebooksResponse,
    NotebooksListNotebooksError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/",
  });
};

/**
 * Create Notebook
 * Create a new notebook with validation and error handling.
 */
export const notebooksCreateNotebook = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<NotebooksCreateNotebookData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    NotebooksCreateNotebookResponse,
    NotebooksCreateNotebookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/",
  });
};

/**
 * Get Notebook
 * Get a specific notebook by ID with ownership verification.
 */
export const notebooksGetNotebook = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<NotebooksGetNotebookData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    NotebooksGetNotebookResponse,
    NotebooksGetNotebookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}",
  });
};

/**
 * Update Notebook
 * Update a notebook with ownership verification and validation.
 */
export const notebooksUpdateNotebook = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<NotebooksUpdateNotebookData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    NotebooksUpdateNotebookResponse,
    NotebooksUpdateNotebookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}",
  });
};

/**
 * Delete Notebook
 * Delete a notebook with comprehensive cleanup including orphaned source handling.
 *
 * This endpoint now handles:
 * - Database deletion with cascade handling
 * - Identification of orphaned sources (not used by other notebooks)
 * - Comprehensive deletion of orphaned sources (Qdrant + MinIO cleanup)
 * - Proper error handling and rollback
 */
export const notebooksDeleteNotebook = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<NotebooksDeleteNotebookData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    NotebooksDeleteNotebookResponse,
    NotebooksDeleteNotebookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}",
  });
};

/**
 * List Notebook Messages
 * List messages in a notebook with ownership verification.
 */
export const notebookMessagesListNotebookMessages = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    NotebookMessagesListNotebookMessagesData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    NotebookMessagesListNotebookMessagesResponse,
    NotebookMessagesListNotebookMessagesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}/messages",
  });
};

/**
 * Add Message To Notebook
 * Add a message to a notebook with validation and ownership verification.
 */
export const notebookMessagesAddMessageToNotebook = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    NotebookMessagesAddMessageToNotebookData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    NotebookMessagesAddMessageToNotebookResponse,
    NotebookMessagesAddMessageToNotebookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}/messages",
  });
};

/**
 * List Notebook Sources
 * List sources in a notebook with ownership verification.
 */
export const notebookSourcesListNotebookSources = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    NotebookSourcesListNotebookSourcesData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    NotebookSourcesListNotebookSourcesResponse,
    NotebookSourcesListNotebookSourcesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}/sources",
  });
};

/**
 * Add Source To Notebook
 * Add a source to a notebook with idempotency and ownership verification.
 */
export const notebookSourcesAddSourceToNotebook = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    NotebookSourcesAddSourceToNotebookData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    NotebookSourcesAddSourceToNotebookResponse,
    NotebookSourcesAddSourceToNotebookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}/sources",
  });
};

/**
 * Remove Source From Notebook
 * Remove a source from a notebook with ownership verification.
 */
export const notebookSourcesRemoveSourceFromNotebook = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    NotebookSourcesRemoveSourceFromNotebookData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).delete<
    NotebookSourcesRemoveSourceFromNotebookResponse,
    NotebookSourcesRemoveSourceFromNotebookError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}/sources/{source_id}",
  });
};

/**
 * Update Notebook Source
 * Update a notebook source relationship (e.g., change position).
 */
export const notebookSourcesUpdateNotebookSource = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    NotebookSourcesUpdateNotebookSourceData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).put<
    NotebookSourcesUpdateNotebookSourceResponse,
    NotebookSourcesUpdateNotebookSourceError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/notebooks/{notebook_id}/sources/{source_id}",
  });
};

/**
 * Create User
 * Create a new user.
 */
export const privateCreateUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<PrivateCreateUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PrivateCreateUserResponse,
    PrivateCreateUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/private/users/",
  });
};
