// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type Body_uploads_upload_files = {
  files: Array<Blob | File>;
};

export type DocumentPublic = {
  filename: string;
  mime_type: string;
  size: number;
  bucket: string;
  object_key: string;
  document_metadata?: string;
  status?: ProcessingStatus;
  version?: number;
  owner_id: string;
  id: string;
  created_at: string;
  updated_at: string;
};

export type DocumentsPublic = {
  data: Array<DocumentPublic>;
  count: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ItemCreate = {
  title: string;
  description?: string | null;
};

export type ItemPublic = {
  title: string;
  description?: string | null;
  id: string;
  owner_id: string;
};

export type ItemsPublic = {
  data: Array<ItemPublic>;
  count: number;
};

export type ItemUpdate = {
  title?: string | null;
  description?: string | null;
};

export type Message = {
  message: string;
};

export type NewPassword = {
  token: string;
  new_password: string;
};

export type NotebookCreate = {
  title: string;
  description?: string | null;
};

export type NotebookMessageCreate = {
  notebook_id: string;
  role: string;
  content: string;
  used_sources?: Array<string> | null;
};

export type NotebookMessagePublic = {
  notebook_id: string;
  role: string;
  content: string;
  used_sources?: Array<string> | null;
  id: string;
  created_at: string;
};

export type NotebookMessagesPublic = {
  data: Array<NotebookMessagePublic>;
  count: number;
};

export type NotebookPublic = {
  title: string;
  description?: string | null;
  owner_id: string;
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Number of sources linked to this notebook
   */
  source_count?: number;
};

export type NotebookSourceCreate = {
  source_id: string;
  position?: number | null;
};

export type NotebookSourcePublic = {
  notebook_id: string;
  source_id: string;
  position?: number | null;
  id: string;
  added_at: string;
  source: SourcePublic;
};

export type NotebookSourcesPublic = {
  data: Array<NotebookSourcePublic>;
  count: number;
};

export type NotebookSourceUpdate = {
  position?: number | null;
};

export type NotebooksPublic = {
  data: Array<NotebookPublic>;
  count: number;
};

export type NotebookUpdate = {
  title?: string | null;
  description?: string | null;
};

export type PrivateUserCreate = {
  email: string;
  password: string;
  full_name: string;
  is_verified?: boolean;
};

export type ProcessingStatus = "pending" | "processing" | "indexed" | "failed";

export type SearchResult = {
  document_id: string;
  filename: string;
  score: number;
  chunk_text: string;
  chunk_index: number;
  doc_metadata: {
    [key: string]: unknown;
  };
};

export type SearchResults = {
  results: Array<SearchResult>;
  total: number;
  query: string;
};

export type SourceCreate = {
  title: string;
  description?: string | null;
  source_type: SourceType;
  source_metadata?: {
    [key: string]: unknown;
  };
};

export type SourcePublic = {
  title: string;
  description?: string | null;
  source_type: SourceType;
  source_metadata?: {
    [key: string]: unknown;
  };
  status?: ProcessingStatus;
  owner_id: string;
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Number of notebooks this source is linked to
   */
  notebook_count?: number;
};

export type SourcesPublic = {
  data: Array<SourcePublic>;
  count: number;
};

export type SourceType = "document" | "url" | "video" | "image" | "text";

export type SourceUpdate = {
  title?: string | null;
  description?: string | null;
  source_metadata?: {
    [key: string]: unknown;
  } | null;
};

export type Token = {
  access_token: string;
  token_type?: string;
};

export type UpdatePassword = {
  current_password: string;
  new_password: string;
};

export type UserCreate = {
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_approved?: boolean;
  full_name?: string | null;
  password: string;
};

export type UserPublic = {
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_approved?: boolean;
  full_name?: string | null;
  id: string;
};

export type UserRegister = {
  email: string;
  password: string;
  full_name?: string | null;
};

export type UsersPublic = {
  data: Array<UserPublic>;
  count: number;
};

export type UserUpdate = {
  email?: string | null;
  is_active?: boolean;
  is_superuser?: boolean;
  is_approved?: boolean | null;
  full_name?: string | null;
  password?: string | null;
};

export type UserUpdateMe = {
  full_name?: string | null;
  email?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type LoginLoginAccessTokenData = {
  body: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = Token;

export type LoginLoginAccessTokenError = HTTPValidationError;

export type LoginTestTokenResponse = UserPublic;

export type LoginTestTokenError = unknown;

export type LoginRecoverPasswordData = {
  path: {
    email: string;
  };
};

export type LoginRecoverPasswordResponse = Message;

export type LoginRecoverPasswordError = HTTPValidationError;

export type LoginResetPasswordData = {
  body: NewPassword;
};

export type LoginResetPasswordResponse = Message;

export type LoginResetPasswordError = HTTPValidationError;

export type LoginRecoverPasswordHtmlContentData = {
  path: {
    email: string;
  };
};

export type LoginRecoverPasswordHtmlContentResponse = string;

export type LoginRecoverPasswordHtmlContentError = HTTPValidationError;

export type UsersReadUsersData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type UsersReadUsersResponse = UsersPublic;

export type UsersReadUsersError = HTTPValidationError;

export type UsersCreateUserData = {
  body: UserCreate;
};

export type UsersCreateUserResponse = UserPublic;

export type UsersCreateUserError = HTTPValidationError;

export type UsersReadWaitlistUsersData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type UsersReadWaitlistUsersResponse = UsersPublic;

export type UsersReadWaitlistUsersError = HTTPValidationError;

export type UsersReadUserMeResponse = UserPublic;

export type UsersReadUserMeError = unknown;

export type UsersDeleteUserMeResponse = Message;

export type UsersDeleteUserMeError = unknown;

export type UsersUpdateUserMeData = {
  body: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = UserPublic;

export type UsersUpdateUserMeError = HTTPValidationError;

export type UsersUpdatePasswordMeData = {
  body: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = Message;

export type UsersUpdatePasswordMeError = HTTPValidationError;

export type UsersRegisterUserData = {
  body: UserRegister;
};

export type UsersRegisterUserResponse = UserPublic;

export type UsersRegisterUserError = HTTPValidationError;

export type UsersReadUserByIdData = {
  path: {
    user_id: string;
  };
};

export type UsersReadUserByIdResponse = UserPublic;

export type UsersReadUserByIdError = HTTPValidationError;

export type UsersUpdateUserData = {
  body: UserUpdate;
  path: {
    user_id: string;
  };
};

export type UsersUpdateUserResponse = UserPublic;

export type UsersUpdateUserError = HTTPValidationError;

export type UsersDeleteUserData = {
  path: {
    user_id: string;
  };
};

export type UsersDeleteUserResponse = unknown;

export type UsersDeleteUserError = HTTPValidationError;

export type UsersApproveUserData = {
  path: {
    user_id: string;
  };
};

export type UsersApproveUserResponse = UserPublic;

export type UsersApproveUserError = HTTPValidationError;

export type UsersRejectUserData = {
  path: {
    user_id: string;
  };
};

export type UsersRejectUserResponse = Message;

export type UsersRejectUserError = HTTPValidationError;

export type UtilsTestEmailData = {
  query: {
    email_to: string;
  };
};

export type UtilsTestEmailResponse = Message;

export type UtilsTestEmailError = HTTPValidationError;

export type UtilsHealthCheckResponse = boolean;

export type UtilsHealthCheckError = unknown;

export type ItemsReadItemsData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type ItemsReadItemsResponse = ItemsPublic;

export type ItemsReadItemsError = HTTPValidationError;

export type ItemsCreateItemData = {
  body: ItemCreate;
};

export type ItemsCreateItemResponse = ItemPublic;

export type ItemsCreateItemError = HTTPValidationError;

export type ItemsReadItemData = {
  path: {
    id: string;
  };
};

export type ItemsReadItemResponse = ItemPublic;

export type ItemsReadItemError = HTTPValidationError;

export type ItemsUpdateItemData = {
  body: ItemUpdate;
  path: {
    id: string;
  };
};

export type ItemsUpdateItemResponse = ItemPublic;

export type ItemsUpdateItemError = HTTPValidationError;

export type ItemsDeleteItemData = {
  path: {
    id: string;
  };
};

export type ItemsDeleteItemResponse = Message;

export type ItemsDeleteItemError = HTTPValidationError;

export type AgentAgentChatProxyResponse = unknown;

export type AgentAgentChatProxyError = unknown;

export type UploadsUploadFilesData = {
  body: Body_uploads_upload_files;
};

export type UploadsUploadFilesResponse = {
  [key: string]: unknown;
};

export type UploadsUploadFilesError = HTTPValidationError;

export type UploadsListDocumentsData = {
  query?: {
    /**
     * Maximum number of records to return
     */
    limit?: number;
    /**
     * Number of records to skip
     */
    skip?: number;
  };
};

export type UploadsListDocumentsResponse = DocumentsPublic;

export type UploadsListDocumentsError = HTTPValidationError;

export type UploadsDeleteDocumentsData = {
  body: Array<string>;
};

export type UploadsDeleteDocumentsResponse = {
  [key: string]: unknown;
};

export type UploadsDeleteDocumentsError = HTTPValidationError;

export type UploadsGetDocumentData = {
  path: {
    document_id: string;
  };
};

export type UploadsGetDocumentResponse = DocumentPublic;

export type UploadsGetDocumentError = HTTPValidationError;

export type UploadsDeleteDocumentData = {
  path: {
    document_id: string;
  };
};

export type UploadsDeleteDocumentResponse = {
  [key: string]: unknown;
};

export type UploadsDeleteDocumentError = HTTPValidationError;

export type UploadsGetPresignedUrlData = {
  query: {
    /**
     * URL expiration time in minutes
     */
    expires_minutes?: number;
    key: string;
  };
};

export type UploadsGetPresignedUrlResponse = {
  [key: string]: unknown;
};

export type UploadsGetPresignedUrlError = HTTPValidationError;

export type UploadsCheckDataConsistencyResponse = {
  [key: string]: unknown;
};

export type UploadsCheckDataConsistencyError = unknown;

export type UploadsCleanupFilesData = {
  query?: {
    /**
     * If True, only report what would be deleted
     */
    dry_run?: boolean;
  };
};

export type UploadsCleanupFilesResponse = {
  [key: string]: unknown;
};

export type UploadsCleanupFilesError = HTTPValidationError;

export type UploadsCleanupRecordsData = {
  query?: {
    /**
     * If True, only report what would be deleted
     */
    dry_run?: boolean;
  };
};

export type UploadsCleanupRecordsResponse = {
  [key: string]: unknown;
};

export type UploadsCleanupRecordsError = HTTPValidationError;

export type UploadsFullCleanupData = {
  query?: {
    /**
     * If True, only report what would be cleaned
     */
    dry_run?: boolean;
  };
};

export type UploadsFullCleanupResponse = {
  [key: string]: unknown;
};

export type UploadsFullCleanupError = HTTPValidationError;

export type SearchSearchDocumentsData = {
  query: {
    /**
     * Maximum number of results
     */
    limit?: number;
    /**
     * Search query
     */
    query: string;
    /**
     * Minimum similarity score
     */
    score_threshold?: number;
  };
};

export type SearchSearchDocumentsResponse = SearchResults;

export type SearchSearchDocumentsError = HTTPValidationError;

export type SearchSearchHealthResponse = {
  [key: string]: unknown;
};

export type SearchSearchHealthError = unknown;

export type SourcesListSourcesData = {
  query?: {
    /**
     * Maximum number of records to return
     */
    limit?: number;
    /**
     * Number of records to skip
     */
    skip?: number;
    /**
     * Filter by source type
     */
    source_type?: SourceType | null;
  };
};

export type SourcesListSourcesResponse = SourcesPublic;

export type SourcesListSourcesError = HTTPValidationError;

export type SourcesCreateSourceData = {
  body: SourceCreate;
};

export type SourcesCreateSourceResponse = SourcePublic;

export type SourcesCreateSourceError = HTTPValidationError;

export type SourcesGetSourceData = {
  path: {
    source_id: string;
  };
};

export type SourcesGetSourceResponse = SourcePublic;

export type SourcesGetSourceError = HTTPValidationError;

export type SourcesUpdateSourceData = {
  body: SourceUpdate;
  path: {
    source_id: string;
  };
};

export type SourcesUpdateSourceResponse = SourcePublic;

export type SourcesUpdateSourceError = HTTPValidationError;

export type SourcesDeleteSourceData = {
  path: {
    source_id: string;
  };
};

export type SourcesDeleteSourceResponse = unknown;

export type SourcesDeleteSourceError = HTTPValidationError;

export type NotebooksListNotebooksData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type NotebooksListNotebooksResponse = NotebooksPublic;

export type NotebooksListNotebooksError = HTTPValidationError;

export type NotebooksCreateNotebookData = {
  body: NotebookCreate;
};

export type NotebooksCreateNotebookResponse = NotebookPublic;

export type NotebooksCreateNotebookError = HTTPValidationError;

export type NotebooksGetNotebookData = {
  path: {
    notebook_id: string;
  };
};

export type NotebooksGetNotebookResponse = NotebookPublic;

export type NotebooksGetNotebookError = HTTPValidationError;

export type NotebooksUpdateNotebookData = {
  body: NotebookUpdate;
  path: {
    notebook_id: string;
  };
};

export type NotebooksUpdateNotebookResponse = NotebookPublic;

export type NotebooksUpdateNotebookError = HTTPValidationError;

export type NotebooksDeleteNotebookData = {
  path: {
    notebook_id: string;
  };
};

export type NotebooksDeleteNotebookResponse = unknown;

export type NotebooksDeleteNotebookError = HTTPValidationError;

export type NotebookMessagesListNotebookMessagesData = {
  path: {
    notebook_id: string;
  };
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type NotebookMessagesListNotebookMessagesResponse =
  NotebookMessagesPublic;

export type NotebookMessagesListNotebookMessagesError = HTTPValidationError;

export type NotebookMessagesAddMessageToNotebookData = {
  body: NotebookMessageCreate;
  path: {
    notebook_id: string;
  };
};

export type NotebookMessagesAddMessageToNotebookResponse =
  NotebookMessagePublic;

export type NotebookMessagesAddMessageToNotebookError = HTTPValidationError;

export type NotebookSourcesListNotebookSourcesData = {
  path: {
    notebook_id: string;
  };
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type NotebookSourcesListNotebookSourcesResponse = NotebookSourcesPublic;

export type NotebookSourcesListNotebookSourcesError = HTTPValidationError;

export type NotebookSourcesAddSourceToNotebookData = {
  body: NotebookSourceCreate;
  path: {
    notebook_id: string;
  };
};

export type NotebookSourcesAddSourceToNotebookResponse = NotebookSourcePublic;

export type NotebookSourcesAddSourceToNotebookError = HTTPValidationError;

export type NotebookSourcesRemoveSourceFromNotebookData = {
  path: {
    notebook_id: string;
    source_id: string;
  };
};

export type NotebookSourcesRemoveSourceFromNotebookResponse = unknown;

export type NotebookSourcesRemoveSourceFromNotebookError = HTTPValidationError;

export type NotebookSourcesUpdateNotebookSourceData = {
  body: NotebookSourceUpdate;
  path: {
    notebook_id: string;
    source_id: string;
  };
};

export type NotebookSourcesUpdateNotebookSourceResponse = NotebookSourcePublic;

export type NotebookSourcesUpdateNotebookSourceError = HTTPValidationError;

export type PrivateCreateUserData = {
  body: PrivateUserCreate;
};

export type PrivateCreateUserResponse = UserPublic;

export type PrivateCreateUserError = HTTPValidationError;
