"""add_status_field_to_source_table

Revision ID: ff9469223647
Revises: 26c933e99533
Create Date: 2025-08-20 06:39:43.191060

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff9469223647'
down_revision = '26c933e99533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the new enum type first
    processingstatus_enum = sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', name='processingstatus')
    processingstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Add status column to source table
    op.add_column('source', sa.Column('status', processingstatus_enum, nullable=False, server_default='PENDING'))
    
    # Update existing document status values to use new enum (they have same values, so this is safe)
    # Note: We'll keep the old enum for now to avoid breaking existing data
    # The enum type change can be done in a separate migration if needed
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'status')
    # Drop the processingstatus enum type
    processingstatus_enum = sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', name='processingstatus')
    processingstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
